### PR TITLE
Update reveal.js, tabs->spaces, marumari's changes, always-current certs graph

### PR DESCRIPTION
**Pull request by jcjones**
- Updated reveal.js to 3.2.0
  - Refactored to match the standard bower directory structure to simplify future upgrades
- Converted all tabs to spaces, as there was a mix ... everywhere
- Pulled in all of @marumari's nice updates
- Changed the Certificates per Day graph to pull direct from plot.ly, so it's always up-to-date.

### CODE REVIEW

**Comment by april** [comment]
Well, I think anything by @marumari, whoever he/she is, is golden, so it definitely gets my r+ from that perspective.  ;)

The only thing I would say is that using plot.ly is great, but it means that the presentation can't be delivered without internet connectivity. Not a big deal (probably), but something to think about. About half of the places I give presentations don't have internet or at least reliable internet.

**Comment by jcjones** [comment]
I'll fiddle up something that fails back to loading the image from the filesystem and update the PR. Thanks!

**Comment by jcjones** [comment]
Ready for re-r?

**Comment by bifurcation** [comment]
Merging this based on @marumari's review.

**Pull request merged**
